version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: duffbot_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: